# Generated by Django 4.0.4 on 2022-04-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_size_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='myapp.tag'),
        ),
    ]
