# Generated by Django 4.0.4 on 2022-04-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_location_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='dog_images')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dog')),
            ],
        ),
    ]
