# Generated by Django 4.0.4 on 2022-04-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='caption',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='is_profile_pic',
            field=models.BooleanField(default=True),
        ),
    ]
