# Generated by Django 4.0.4 on 2022-04-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_options'),
        ('myapp', '0006_add_profile_permissions'),
    ]

    operations = [
    ]
