# Generated by Django 4.0.4 on 2022-04-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='myapp/dog-images/'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('dog_initializer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initializer', to='myapp.dog')),
                ('dog_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='myapp.dog')),
            ],
        ),
    ]
