# Generated by Django 4.0.4 on 2022-04-22 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_image_image_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='myapp.dog')),
                ('dog_other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other', to='myapp.dog')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=3000, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.conversation')),
                ('dog_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='myapp.dog')),
                ('dog_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='myapp.dog')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.CharField(blank=True, max_length=3000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
